nginx:
    build: ./containers-services/nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./containers-services/node
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./containers-services/node
    links:
        - redis
    ports:
        - "8080"
    # volumes:
    #     - "./containers-services/switcher-node:/src"
node3:
    build: ./containers-services/node
    links:
        - redis
    ports:
        - "8080"
    # volumes:
    #     - "./containers-services/switcher-node:/src"
redis:
    image: redis
    ports:
        - "6379"
